// Google Business Profile categories (commonly used subset)
// Source: Google Business Profile supported categories
export const GOOGLE_BUSINESS_CATEGORIES: string[] = [
  "Accountant",
  "Acupuncture clinic",
  "Adult day care center",
  "Advertising agency",
  "Air conditioning contractor",
  "Air duct cleaning service",
  "Aircraft rental service",
  "Airline",
  "Airport",
  "Alterations and repairs",
  "Animal hospital",
  "Animal shelter",
  "Antique furniture restoration service",
  "Antique store",
  "Apartment building",
  "Apartment complex",
  "Appliance repair service",
  "Appliance store",
  "Appraiser",
  "Aquarium",
  "Arcade",
  "Architect",
  "Art gallery",
  "Art school",
  "Art studio",
  "Asbestos testing service",
  "Assisted living facility",
  "Attorney",
  "Auction house",
  "Audio visual equipment repair service",
  "Auto body shop",
  "Auto broker",
  "Auto detailing service",
  "Auto glass shop",
  "Auto parts store",
  "Auto radiator repair service",
  "Auto repair shop",
  "Auto wrecker",
  "Automated teller machine",
  "Automobile storage facility",
  "Awning supplier",
  "Bail bonds service",
  "Bakery",
  "Bank",
  "Bar",
  "Barbecue restaurant",
  "Barber shop",
  "Baseball field",
  "Batting cage center",
  "Beauty salon",
  "Beauty school",
  "Beauty supply store",
  "Bed and breakfast inn",
  "Bicycle repair shop",
  "Bicycle shop",
  "Billiards supply store",
  "Blood bank",
  "Board game cafe",
  "Boat dealer",
  "Boat rental service",
  "Bookkeeper",
  "Bookstore",
  "Botanical garden",
  "Bottled water supplier",
  "Bowling alley",
  "Brake shop",
  "Brewery",
  "Bridal shop",
  "Building material supplier",
  "Burger restaurant",
  "Business center",
  "Business management consultant",
  "Cabinet maker",
  "Cable company",
  "Cafe",
  "Camera store",
  "Camping store",
  "Car dealer",
  "Car detailing service",
  "Car inspection station",
  "Car rental agency",
  "Car wash",
  "Cargo shipping service",
  "Carpet cleaning service",
  "Carpet installer",
  "Carpet store",
  "Catering food and drink supplier",
  "Cell phone store",
  "Cemetery",
  "Check cashing service",
  "Cheese shop",
  "Child care agency",
  "Chiropractor",
  "Church",
  "Civil engineer",
  "Cleaning products supplier",
  "Cleaners",
  "Clothing store",
  "Coffee shop",
  "Coin operated laundry equipment supplier",
  "Collection agency",
  "Community center",
  "Computer consultant",
  "Computer repair service",
  "Computer store",
  "Concert hall",
  "Concrete contractor",
  "Construction company",
  "Convenience store",
  "Cosmetics store",
  "Counselor",
  "Courier service",
  "Credit counseling service",
  "Credit union",
  "Cruise agency",
  "Custom home builder",
  "Dance school",
  "Deck builder",
  "Dental clinic",
  "Dentist",
  "Department store",
  "Dermatologist",
  "Diner",
  "Discount store",
  "Dog daycare center",
  "Dog groomer",
  "Dog trainer",
  "Doughnut shop",
  "Draft Beer bar",
  "Drug store",
  "Dry cleaner",
  "Drywall contractor",
  "Electrician",
  "Electronics repair shop",
  "Electronics store",
  "Emergency care physician",
  "Emergency locksmith service",
  "Employment agency",
  "Environmental consultant",
  "Equipment rental agency",
  "Escape room center",
  "Event management company",
  "Event venue",
  "Excavating contractor",
  "Eye care center",
  "Facial spa",
  "Family day care provider",
  "Family practice physician",
  "Farm",
  "Fast food restaurant",
  "Fence contractor",
  "Financial consultant",
  "Fire protection service",
  "Fish and chips restaurant",
  "Fitness center",
  "Floor refinishing service",
  "Flooring contractor",
  "Flooring store",
  "Florist",
  "Food bank",
  "Foundation repair service",
  "Frame store",
  "Freight forwarding service",
  "Funeral home",
  "Furniture maker",
  "Furniture rental service",
  "Furniture repair shop",
  "Furniture store",
  "Garage builder",
  "Garage door supplier",
  "Gas station",
  "General contractor",
  "General practitioner",
  "Gift shop",
  "Glass repair service",
  "Golf club",
  "Golf course",
  "Graphic designer",
  "Grocery store",
  "Gutter cleaning service",
  "Gym",
  "Hair removal service",
  "Hair salon",
  "Handyman",
  "Hardware store",
  "Heating contractor",
  "Home goods store",
  "Home health care service",
  "Home inspector",
  "Home security company",
  "Home theater store",
  "Hospital",
  "Hotel",
  "House cleaning service",
  "HVAC contractor",
  "Ice cream shop",
  "Immigration attorney",
  "Indoor cycling",
  "Insulation contractor",
  "Insurance agency",
  "Insurance broker",
  "Interior designer",
  "Investment service",
  "Italian restaurant",
  "Janitorial service",
  "Jewelry designer",
  "Jewelry store",
  "Junk removal service",
  "Kitchen remodeler",
  "Landscaper",
  "Laser hair removal service",
  "Laundry service",
  "Law firm",
  "Lawn care service",
  "Legal services",
  "Life coach",
  "Lighting store",
  "Limousine service",
  "Loan agency",
  "Locksmith",
  "Lodge",
  "Luggage storage facility",
  "Lumber store",
  "Maid service",
  "Makeup artist",
  "Marketing consultant",
  "Martial arts school",
  "Massage therapist",
  "Mattress store",
  "Mechanic",
  "Medical clinic",
  "Medical spa",
  "Mexican restaurant",
  "Microwave oven repair service",
  "Mobile home dealer",
  "Money order service",
  "Mortgage broker",
  "Mortgage lender",
  "Motorcycle dealer",
  "Motorcycle repair shop",
  "Moving and storage service",
  "Moving company",
  "Nail salon",
  "Notary public",
  "Nursery school",
  "Nutritionist",
  "Office supply store",
  "Oil change service",
  "Ophthalmologist",
  "Optician",
  "Optometrist",
  "Oral surgeon",
  "Orthodontist",
  "Orthopedic surgeon",
  "Outdoor furniture store",
  "Packaging supply store",
  "Painter",
  "Park",
  "Parking garage",
  "Parking lot",
  "Party planner",
  "Pawn shop",
  "Pediatric dentist",
  "Pediatrician",
  "Personal injury attorney",
  "Personal trainer",
  "Pest control service",
  "Pet boarding service",
  "Pet groomer",
  "Pet sitter",
  "Pet store",
  "Pet supply store",
  "Pharmacy",
  "Photo lab",
  "Photographer",
  "Physical therapist",
  "Physical therapy clinic",
  "Piano store",
  "Pizza delivery",
  "Pizza restaurant",
  "Plastic surgeon",
  "Plumber",
  "Pool cleaning service",
  "Pool contractor",
  "Pressure washing service",
  "Printer repair service",
  "Printing service",
  "Private investigator",
  "Property management company",
  "Psychiatrist",
  "Psychologist",
  "Public notary",
  "Railing contractor",
  "Real estate agency",
  "Real estate agent",
  "Real estate appraiser",
  "Real estate attorney",
  "Refrigerator repair service",
  "Remodeler",
  "Rental agency",
  "Restaurant",
  "Roofing contractor",
  "Roofing supply store",
  "RV dealer",
  "RV repair shop",
  "Screen printing service",
  "Security guard service",
  "Security system installer",
  "Self storage facility",
  "Septic system service",
  "Sewer service",
  "Sheet metal contractor",
  "Shoe repair shop",
  "Shoe store",
  "Sign shop",
  "Skin care clinic",
  "Social worker",
  "Solar energy company",
  "Spa",
  "Sports bar",
  "Sporting goods store",
  "Stucco contractor",
  "Supermarket",
  "Sushi restaurant",
  "Swimming pool contractor",
  "Tailor",
  "Tax preparation service",
  "Taxi service",
  "Thai restaurant",
  "Tile contractor",
  "Tire shop",
  "Title company",
  "Towing service",
  "Transportation service",
  "Travel agency",
  "Tree service",
  "Truck dealer",
  "Truck repair shop",
  "Tutoring service",
  "Upholstery shop",
  "Used car dealer",
  "Urgent care center",
  "Vacation home rental agency",
  "Veterinarian",
  "Video production service",
  "Water damage restoration service",
  "Water heater installer",
  "Water softening equipment supplier",
  "Web designer",
  "Wedding photographer",
  "Wedding planner",
  "Weight loss service",
  "Welding supply store",
  "Window cleaning service",
  "Window installation service",
  "Window tinting service",
  "Winery",
  "Yoga studio",
];
